/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SetupOwnerRouteImport } from './routes/setup/owner'
import { Route as SetupOidcRouteImport } from './routes/setup/oidc'
import { Route as SetupCompleteRouteImport } from './routes/setup/complete'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupOwnerRoute = SetupOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => SetupRoute,
} as any)
const SetupOidcRoute = SetupOidcRouteImport.update({
  id: '/oidc',
  path: '/oidc',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCompleteRoute = SetupCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SetupRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/auth/callback'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/auth/callback'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/owner': {
      id: '/setup/owner'
      path: '/owner'
      fullPath: '/setup/owner'
      preLoaderRoute: typeof SetupOwnerRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/oidc': {
      id: '/setup/oidc'
      path: '/oidc'
      fullPath: '/setup/oidc'
      preLoaderRoute: typeof SetupOidcRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/complete': {
      id: '/setup/complete'
      path: '/complete'
      fullPath: '/setup/complete'
      preLoaderRoute: typeof SetupCompleteRouteImport
      parentRoute: typeof SetupRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SetupRouteChildren {
  SetupCompleteRoute: typeof SetupCompleteRoute
  SetupOidcRoute: typeof SetupOidcRoute
  SetupOwnerRoute: typeof SetupOwnerRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCompleteRoute: SetupCompleteRoute,
  SetupOidcRoute: SetupOidcRoute,
  SetupOwnerRoute: SetupOwnerRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
